### ISSUE TITLE
ParseException raised on valid Hjson.

### ISSUE THREAD

**Issue by Stephan972** [hjson/hjson-java#7]
The small hjson below is turned into Json on https://hjson.org/try.html:

    [
       {
          foo : "
          "
       }
    ]

When this same small hjson is given to hjson-java, the following exception is raised:

    Exception in thread "main" org.hjson.ParseException: Expected valid string character at 3:8
      at org.hjson.HjsonParser.error(HjsonParser.java:482)
      at org.hjson.HjsonParser.expected(HjsonParser.java:476)
      at org.hjson.HjsonParser.readStringInternal(HjsonParser.java:280)
      at org.hjson.HjsonParser.readString(HjsonParser.java:272)
      at org.hjson.HjsonParser.readValue(HjsonParser.java:106)
      at org.hjson.HjsonParser.readObject(HjsonParser.java:189)
      at org.hjson.HjsonParser.readValue(HjsonParser.java:108)
      at org.hjson.HjsonParser.readArray(HjsonParser.java:163)
      at org.hjson.HjsonParser.readValue(HjsonParser.java:107)
      at org.hjson.HjsonParser.parse(HjsonParser.java:81)
      at org.hjson.JsonValue.readHjson(JsonValue.java:130)
      at my.HjsonPOC.main(HjsonPOC.java:16)

Here is a snippet to reproduce the problem:

    String test = "[\r\n" + //
        " {\r\n" + //
        " foo : \"\r\n" + //
        " \"\r\n" + //
        " }\r\n" + //
        "]";

    String jsonString = JsonValue.readHjson(test).toString(); //  ParseException raised !
    // Expected Json string:
    //[
    //  {
    //    "foo": "\r\n      "
    //  }
    //]

**Comment by laktak** [comment]
Sorry, there was a bug in the JS implementation. I fixed it and added a test case.

You can use multiline strings for your case:

```
{ 
  test: 
    '''
    abc
    def
    '''
}
```
